[package]
name = "treasurehunt"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
aptos_token_objects = "0x4"

clicker="0xd8394de15fde937b0d4f3e5f9a6d121027cca25ff20080a72c187a1656bbb231"

admin="0x384e639804ae5baf16cd0ee3f5964dc32363490afe7ca49562cc2fcaac431fdb"

ExGuiToken="0xd8394de15fde937b0d4f3e5f9a6d121027cca25ff20080a72c187a1656bbb231"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
