[package]
name = "treasurehunt_smartcontract"
version = "1.0.0"
authors = []

[addresses]
clicker="0x78dda626402a433a67bfe22665172c152e74e131f91f6e049d2e9e5064b8140d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
