[package]
name = "treasurehunt"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
aptos_token_objects = "0x4"

clicker="0x9edfe2114d0decccc31e087ac0fbc951cae1aec220a048f08cc68742282ef985"

admin="0x3af74d5b92e92ef047af5aa1c77864bc704612977dcade28ae56a2b226b80913"

ExGuiToken="0x9edfe2114d0decccc31e087ac0fbc951cae1aec220a048f08cc68742282ef985"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
