[package]
name = "treasurehunt"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
aptos_token_objects = "0x4"

clicker="0x12d8d68c60024dd966e23e1cae432ca924119250cdb53122f56dcedde56bb394"

admin="0x6174af4a891b6fcabba00649d61892b526570008c1480085aa6b979498e78b6f"

ExGuiToken="0x12d8d68c60024dd966e23e1cae432ca924119250cdb53122f56dcedde56bb394"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
